In [ ]:
import numpy as np


a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3], [4,5,6]])
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [ ]:
# functions to create arrays
a = np.zeros((2,2)) # np.array with zeros in shape (2,2)
print(a)

b = np.ones((1,2)) # np.array with all ones
print(b)

c = np.full ((2,2), 7)  # constant array with specified value (7)
print(c)

d = np.eye(2) # 2x2 identity matrix
print(d)

e = np.random.random((2,2)) # random matrix of specified shape
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.91515944 0.85570948]
 [0.8624181  0.62456165]]


In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# """
# 1  2  3  4
# 5  6  7  8
# 9  10 11 12
# """
print(a)


# get first two rows, and middle columns
b = a[:2, 1:3] # pull out subarrays
print(b)
# """
# 2 3
# 6 7
# """

# slive of array is view into same data, so modifying it will modify the original data
print(a[0, 1]) # 2
b[0,0] = 77
print(a[0, 1])
# """
# 1 77 3 4
# 5  6 7 8
# 9 10 11 12
# """


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


In [ ]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])



row_r1 = a[1, :]  # rank 1 view of second row of a
row_r2 = a[1:2, :] # rank 2 view of second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape) 

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
# integer array indexing
# when using slicing to index into np arrays, resulting array is always a subarray/view of original array
# integer array indexing allows you to construct arbitrary arrays using data from other arrays

a = np.array([[1,2], [3,4], [5,6]])
"""
1 2
3 4
5 6
"""

print(a[[0,1,2], [0,1,0]]) 
# first elements (0,0) correspond to 1
# second elements (1,1) correspond to 4
# third elements (2,0) correspond to 5

[1 4 5]


In [ ]:
# trick: select or mutate one element from each row (or column) of matrix
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(a)

b = np.array([0,2,0,1])


print("np.arange ", np.arange(4))
print(a[np.arange(4), b])

a[np.arange(4), b] += 10

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
np.arange  [0 1 2 3]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [ ]:
# boolean array indexing
a = np.array([[1,2], [3,4], [5,6]])

bool_idx = (a>2)  # find elements of a that are bigger than 2

print(bool_idx)

print(a[bool_idx])  # constructs rank 1 array corresponding to the true values

print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [14]:
# Datatypes

x = np.array([1,2])
print(x.dtype)

x = np.array([1.0, 2.0])
print(x.dtype)

x = np.array([1,2], dtype=np.int64)
print(x.dtype)

int64
float64
int64


In [15]:
# array math (all of these are element-wise)
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

print(x+y)
print(np.add(x,y))


print(x-y)
print(np.subtract(x,y))


print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))


print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [16]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(v.dot(w)) # inner product of vectors v and w
print(np.dot(v,w))

print(x.dot(v))
print(np.dot(x,v))

print(x.dot(y)) # matrix multiplication
print(np.dot(x,y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [2]:
import numpy as np
x = np.array([[1,2], [3,4]])
print(np.sum(x))  # sum of all elements

print(np.sum(x, axis=0))  # sum over columns
print(np.sum(x, axis=1))  # sum over rows

10
[4 6]
[3 7]


In [3]:
x = np.array([[1,2], [3,4]])
print(x)
print(x.T)

v = np.array([1,2,3]) # taking transpose of rank 1 array does nothing
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [4]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) # empty matrix of shape x


for i in range(4):
  y[i,:] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [5]:
# same functionality in block above --> like so:

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
vv = np.tile(v,(4,1))
print(vv)


y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [6]:
# numpy broadcasting lets us do this with even less work
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
# line works even though both objects are of different shapes
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [9]:
v = np.array([1,2,3]) # v has shape (3,)
w = np.array([4,5]) # w has shape (2,)


print(np.reshape(v, (3,1)) * w)

x = np.array([[1,2,3], [4,5,6]])
print(x+v)



print((x.T+w).T)

print(x+np.reshape(w, (2,1)))


print(x*2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
